### ISSUE TITLE
UI Improvements for the Discussion page

### ISSUE THREAD

**Issue by akirk** [akirk/gp-translation-helpers#69]
Relaying these reports by @La-Geek:

- [x] #73 Asterisk is not explained

![Screenshot 2022-07-06 at 10 01 45](https://user-images.githubusercontent.com/203408/177502113-f080c31c-40f9-48d6-a856-245a9a8a522e.png)
We need to add a `* mandatory field` or similar.

- [ ] Consider adding an option "Other"
![Screenshot 2022-07-06 at 10 09 11](https://user-images.githubusercontent.com/203408/177502229-0c6ca27d-8a74-4e66-9fcb-271ea4470c21.png)
Sometimes a message doesn't fit in the categories. Should we add such a topic? Who should be notified? Possibly no-one

- [x] #71 Add a help bubble to explain who will be notified
If we add an "Other" topic, it should be possible to see that nobody will be notified here.

- [x] #83  Make the Reply link/button more prominent
![Screenshot 2022-07-06 at 10 02 04](https://user-images.githubusercontent.com/203408/177502608-fdc2f0e7-b2f2-4086-89e6-161672b450d9.png)
Maybe visually make it a button?

- [x] #82 Display Reject reason text, not value
![Screenshot 2022-07-06 at 10 02 04](https://user-images.githubusercontent.com/203408/177502792-ccf4dcb2-6faa-4bae-bf75-6dd01f0898cc.png)
Here it says just "grammar", i.e. [the reject reason key, not the value](https://github.com/GlotPress/gp-translation-helpers/blob/e1809688cf960c90dcf9169764d15f47f871f166/helpers/helper-translation-discussion.php#L727).

- [x] #79 Improve the header section for long originals and translations
<img width="920" alt="image (2)" src="https://user-images.githubusercontent.com/203408/177503187-901b4ab6-5e19-4d30-b7b6-c93b3d4f26bd.png">
Maybe decrease the font-size beyond a certain character threshold?

**Comment by La-Geek** [comment]
> Asterisk is not explained

That is not what I meant. It is well known that an asterisk means "mandatory". What I wanted to say: There are only 3 topics and one of them must be selected (asterisk = mandatory). So you can not talk about other topics. 

It looked to me like that was the only way to communicate/discuss. I had not seen or correctly assigned the reply links.

**Comment by akirk** [comment]
Thank you for clarifying! I think an asterisk can also mean optional, if nothing else it's good practice to explain it which is why I also added it to the list.

**Comment by akirk** [comment]
I have updated the issue with our changes. Only the "Other" reason part remains for now where we don't have agreeement on doing this yet.
